name: fortefy
description: "Aplicacao desnvolvida para a disciplina de Resolucao de Problemas II"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.0
  pix_flutter: ^2.2.0
  postgres: ^3.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/moca.jpeg
    - assets/homem.jpeg
    - assets/fortefy_logo.png
